import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

def visualize_results(df):
    print("--- [3/3] Đang vẽ biểu đồ kiểm nghiệm các giả thuyết ---")

    # Cấu hình giao diện chuẩn học thuật
    sns.set_theme(style="whitegrid", font_scale=1.1)

    # Chuẩn bị dữ liệu vẽ biểu đồ
    df['Risk_Label'] = df['Risk'].map({0.0: 'Rủi ro Thấp', 1.0: 'Rủi ro Cao'})
    df['Subj_Label'] = df['Subj'].map({0.0: 'Khách quan', 1.0: 'Chủ quan'})
    df['Info_Label'] = df['Info'].map({0.0: 'Tải thấp', 1.0: 'Tải cao'})

    # Chia nhóm Literacy (Am hiểu AI) thông qua trung vị
    median_lit = df['Lit_Norm'].median()
    df['Lit_Group'] = df['Lit_Norm'].apply(lambda x: 'Am hiểu Cao' if x > median_lit else 'Am hiểu Thấp')

    # Chia nhóm D_total (Cường độ Mâu thuẫn)
    median_d = df['D_total'].median()
    df['Conflict_Level'] = df['D_total'].apply(lambda x: 'Mâu thuẫn Cao' if x > median_d else 'Mâu thuẫn Thấp')

    # CHART 1: H1 (D_total -> WOA)
    plt.figure(figsize=(6, 6))
    ax1 = sns.barplot(data=df, x='Conflict_Level', y='WOA', hue='Conflict_Level', palette='pastel', legend=False, errorbar=None)
    plt.title('H1: Tác động của Cường độ Mâu thuẫn lên Hành vi', fontweight='bold')
    plt.ylabel('Tỷ lệ chọn Con người (P_human)')
    plt.xlabel('Mức độ Mâu thuẫn (D_total)')
    plt.ylim(0, 1.1)
    for i in ax1.containers: ax1.bar_label(i, fmt='%.2f', padding=3)
    plt.tight_layout()
    plt.savefig('Chart_H1_Conflict.png', dpi=300)
    plt.close()

    # CHART 2: H2 (Trust -> WOA)
    plt.figure(figsize=(8, 6))
    sns.regplot(data=df, x='Trust_Norm', y='WOA', logistic=True, scatter_kws={'alpha': 0.3}, line_kws={'color': 'red'})
    plt.title('H2: Tác động của Niềm tin (Trust) lên Hành vi lựa chọn', fontweight='bold')
    plt.ylabel('Xác suất chọn Con người (WOA)')
    plt.xlabel('Niềm tin vào AI (Trust_Norm)')
    plt.ylim(-0.05, 1.05)
    plt.tight_layout()
    plt.savefig('Chart_H2_Trust_Behavior.png', dpi=300)
    plt.close()

    # CHART 3: H3 (Risk x Subj -> WOA)
    plt.figure(figsize=(8, 6))
    ax3 = sns.barplot(data=df, x='Risk_Label', y='WOA', hue='Subj_Label', palette='Set2', errorbar=None)
    plt.title('H3: Rủi ro khuếch đại tính Chủ quan (Risk x Subj)', fontweight='bold')
    plt.ylabel('Tỷ lệ chọn Con người (P_human)')
    plt.xlabel('Mức độ Rủi ro')
    plt.ylim(0, 1.1)
    plt.axhline(0.5, linestyle='--', color='gray', alpha=0.5)
    for i in ax3.containers: ax3.bar_label(i, fmt='%.2f', padding=3)
    plt.legend(title='Lĩnh vực vấn đề', loc='upper right')
    plt.tight_layout()
    plt.savefig('Chart_H3_Risk_Subj_WOA.png', dpi=300)
    plt.close()

    # CHART 4: H4 (Subj -> Trust)
    plt.figure(figsize=(6, 6))
    ax4 = sns.barplot(data=df, x='Subj_Label', y='Trust_Norm', hue='Subj_Label', palette='Set3', legend=False, errorbar=None)
    plt.title('H4 (a,b): Tính chủ quan tác động Niềm tin', fontweight='bold')
    plt.ylabel('Mức độ Niềm tin vào AI (Trust)')
    plt.xlabel('Lĩnh vực vấn đề')
    plt.ylim(0, 1.1)
    for i in ax4.containers: ax4.bar_label(i, fmt='%.2f', padding=3)
    plt.tight_layout()
    plt.savefig('Chart_H4_Subj_Trust.png', dpi=300)
    plt.close()

    # CHART 5: H5 (Risk x Lit -> Trust)
    plt.figure(figsize=(8, 6))
    sns.pointplot(data=df, x='Risk_Label', y='Trust_Norm', hue='Lit_Group', dodge=True, palette='Blues', markers=['o', 's'])
    plt.title('H5 (a,b): Am hiểu AI điều tiết Rủi ro lên Niềm tin', fontweight='bold')
    plt.ylabel('Mức độ Niềm tin vào AI (Trust)')
    plt.xlabel('Mức độ Rủi ro')
    plt.ylim(0, 1.05)
    plt.legend(title='Mức độ Am hiểu AI (Literacy)')
    plt.tight_layout()
    plt.savefig('Chart_H5_Risk_Lit_Trust.png', dpi=300)
    plt.close()

    # CHART 6: H6 (Info -> WOA)
    plt.figure(figsize=(6, 6))
    ax6 = sns.barplot(data=df, x='Info_Label', y='WOA', hue='Info_Label', palette='viridis', legend=False, errorbar=None)
    plt.title('H6: Tác động của Tải lượng thông tin (Info Load)', fontweight='bold')
    plt.ylabel('Tỷ lệ chọn Con người (P_human)')
    plt.xlabel('Tải lượng thông tin')
    plt.ylim(0, 1.1)
    for i in ax6.containers: ax6.bar_label(i, fmt='%.2f', padding=3)
    plt.tight_layout()
    plt.savefig('Chart_H6_InfoLoad.png', dpi=300)
    plt.close()

    # CHART 7: H7 (Subj x Lit -> Trust)
    plt.figure(figsize=(8, 6))
    sns.pointplot(data=df, x='Subj_Label', y='Trust_Norm', hue='Lit_Group', dodge=True, palette='Oranges', markers=['^', 'v'])
    plt.title('H7: Am hiểu AI điều tiết Tính chủ quan lên Niềm tin', fontweight='bold')
    plt.ylabel('Mức độ Niềm tin vào AI (Trust)')
    plt.xlabel('Lĩnh vực vấn đề')
    plt.ylim(0, 1.05)
    plt.legend(title='Mức độ Am hiểu AI (Literacy)')
    plt.tight_layout()
    plt.savefig('Chart_H7_Subj_Lit_Trust.png', dpi=300)
    plt.close()

    # CHART 8: H8 (Risk x Info -> WOA)
    plt.figure(figsize=(8, 6))
    ax8 = sns.barplot(data=df, x='Risk_Label', y='WOA', hue='Info_Label', palette='magma', errorbar=None)
    plt.title('H8: Tải thông tin suy yếu Rủi ro (Risk x Info)', fontweight='bold')
    plt.ylabel('Tỷ lệ chọn Con người (P_human)')
    plt.xlabel('Mức độ Rủi ro')
    plt.ylim(0, 1.1)
    for i in ax8.containers: ax8.bar_label(i, fmt='%.2f', padding=3)
    plt.legend(title='Tải lượng thông tin', loc='upper right')
    plt.tight_layout()
    plt.savefig('Chart_H8_Risk_Info_WOA.png', dpi=300)
    plt.close()

    # CHART 9: H10 (Risk x Subj -> Trust)
    plt.figure(figsize=(8, 6))
    ax9 = sns.barplot(data=df, x='Risk_Label', y='Trust_Norm', hue='Subj_Label', palette='coolwarm', errorbar=None)
    plt.title('H10: Rủi ro điều tiết Tính chủ quan lên Niềm tin', fontweight='bold')
    plt.ylabel('Mức độ Niềm tin vào AI (Trust)')
    plt.xlabel('Mức độ Rủi ro')
    plt.ylim(0, 1.1)
    for i in ax9.containers: ax9.bar_label(i, fmt='%.2f', padding=3)
    plt.legend(title='Lĩnh vực vấn đề', loc='upper right')
    plt.tight_layout()
    plt.savefig('Chart_H10_Risk_Subj_Trust.png', dpi=300)
    plt.close()

    print("-> Đã tạo và lưu thành công 9 Biểu đồ KHÔNG CẢNH BÁO, CHỈN CHU, SẮC NÉT!")